spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 3000
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - https://death-client-nine.vercel.app
      - https://gotggam.com
      - https://dev-api.gotggam.com
  swagger:
    server-url: ${SWAGGER_SERVER_URL:https://api.gotggam.com}

logging:
  level:
    root: warn
    com.nexters.gotggam: info
